<?php
        $config = array(
            "jq" => "0",
            "sinauser" => "pxn626@live.cn",
            "sinapwd" => "6z687338",
            "cookie" => "",
            "time" => "",
            "token" => "361475298425",
            "wate" => "0",
            "type" => "text",
            "watePositon" => "6",
            "wateAlpha" => "80",
            "wateContent" => "",
            "wateSize" => "40",
            "wateAngle" => "0",
            "wateFont" => "1.TTF",
            "wateColor1" => "255",
            "wateColor2" => "255",
            "wateColor3" => "255",
            "copy" => "0",
        );